name: CMake

on:
  push:
    branches: [ v3.61, main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    # runs-on: ubuntu-latest
    name: "Run for ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ] 
        compiler: [ latest, gcc-9, gcc-10, g++-11, clang, clang-11, clang++-12 ]
        exclude:
          - os: windows-latest
            compiler: gcc-9
          - os: windows-latest
            compiler: gcc-10
          - os: windows-latest
            compiler: g++-11
          - os: windows-latest
            compiler: clang
          - os: windows-latest
            compiler: clang-11
          - os: windows-latest
            compiler: clang++-12
          - os: macos-latest
            compiler: latest
          - os: macos-latest
            compiler: gcc-9
          - os: macos-latest
            compiler: gcc-10
          - os: macos-latest
            compiler: g++-11
          - os: ubuntu-latest
            compiler: latest
          - os: ubuntu-latest
            compiler: clang
          - os: ubuntu-latest
            compiler: clang-11
          - os: ubuntu-latest
            compiler: clang++-12

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install compiler
        id: install_cc
        uses: rlalik/setup-cpp-compiler@v1.1
        with:
          compiler: ${{ matrix.compiler }}
      
      - name: Check compiler
        shell: bash
        env:
          CC: ${{ steps.install_cc.outputs.cc }}
          CXX: ${{ steps.install_cc.outputs.cxx }}
        run: |
          $CC --version
          $CXX --version

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_CI=ON
        #run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_NUMBER_LNS=ON 

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.  
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -V -C ${{env.BUILD_TYPE}}
      
